export const DUMMY_DATA = [
  {
    id: 1,
    product: 'Laptop',
    unitPrice: 1200.0,
    amount: 2,
    totalPrice: 2400.0,
  },
  {
    id: 2,
    product: 'Smartphone',
    unitPrice: 800.0,
    amount: 3,
    totalPrice: 2400.0,
  },
  {
    id: 3,
    product: 'Headphones',
    unitPrice: 150.0,
    amount: 4,
    totalPrice: 600.0,
  },
  {
    id: 4,
    product: 'Keyboard',
    unitPrice: 100.0,
    amount: 5,
    totalPrice: 500.0,
  },
  {
    id: 5,
    product: 'Monitor',
    unitPrice: 300.0,
    amount: 2,
    totalPrice: 600.0,
  },
  {
    id: 6,
    product: 'Mouse',
    unitPrice: 50.0,
    amount: 10,
    totalPrice: 500.0,
  },
  {
    id: 7,
    product: 'Webcam',
    unitPrice: 200.0,
    amount: 1,
    totalPrice: 200.0,
  },
  {
    id: 8,
    product: 'Printer',
    unitPrice: 250.0,
    amount: 3,
    totalPrice: 750.0,
  },
  {
    id: 9,
    product: 'Scanner',
    unitPrice: 300.0,
    amount: 2,
    totalPrice: 600.0,
  },
  {
    id: 10,
    product: 'Tablet',
    unitPrice: 400.0,
    amount: 4,
    totalPrice: 1600.0,
  },
  {
    id: 11,
    product: 'External Hard Drive',
    unitPrice: 100.0,
    amount: 5,
    totalPrice: 500.0,
  },
  {
    id: 12,
    product: 'USB Flash Drive',
    unitPrice: 20.0,
    amount: 25,
    totalPrice: 500.0,
  },
  {
    id: 13,
    product: 'Router',
    unitPrice: 150.0,
    amount: 2,
    totalPrice: 300.0,
  },
  {
    id: 14,
    product: 'Switch',
    unitPrice: 80.0,
    amount: 4,
    totalPrice: 320.0,
  },
  {
    id: 15,
    product: 'Projector',
    unitPrice: 600.0,
    amount: 1,
    totalPrice: 600.0,
  },
  {
    id: 16,
    product: 'Speakers',
    unitPrice: 120.0,
    amount: 3,
    totalPrice: 360.0,
  },
  {
    id: 17,
    product: 'Microphone',
    unitPrice: 80.0,
    amount: 2,
    totalPrice: 160.0,
  },
  {
    id: 18,
    product: 'Camera',
    unitPrice: 700.0,
    amount: 1,
    totalPrice: 700.0,
  },
  {
    id: 19,
    product: 'Tripod',
    unitPrice: 60.0,
    amount: 5,
    totalPrice: 300.0,
  },
  {
    id: 20,
    product: 'Lighting Kit',
    unitPrice: 250.0,
    amount: 2,
    totalPrice: 500.0,
  },
  {
    id: 21,
    product: 'Memory Card',
    unitPrice: 30.0,
    amount: 10,
    totalPrice: 300.0,
  },
  {
    id: 22,
    product: 'VR Headset',
    unitPrice: 400.0,
    amount: 1,
    totalPrice: 400.0,
  },
  {
    id: 23,
    product: 'Drone',
    unitPrice: 1000.0,
    amount: 1,
    totalPrice: 1000.0,
  },
  {
    id: 24,
    product: 'Smartwatch',
    unitPrice: 200.0,
    amount: 3,
    totalPrice: 600.0,
  },
  {
    id: 25,
    product: 'Fitness Tracker',
    unitPrice: 150.0,
    amount: 4,
    totalPrice: 600.0,
  },
  {
    id: 26,
    product: 'Gaming Console',
    unitPrice: 500.0,
    amount: 2,
    totalPrice: 1000.0,
  },
  {
    id: 27,
    product: 'Smart TV',
    unitPrice: 900.0,
    amount: 1,
    totalPrice: 900.0,
  },
  {
    id: 28,
    product: 'Bluetooth Speaker',
    unitPrice: 120.0,
    amount: 3,
    totalPrice: 360.0,
  },
  {
    id: 29,
    product: 'Portable Charger',
    unitPrice: 50.0,
    amount: 4,
    totalPrice: 200.0,
  },
  {
    id: 30,
    product: 'Wireless Earbuds',
    unitPrice: 80.0,
    amount: 5,
    totalPrice: 400.0,
  },
  {
    id: 31,
    product: 'Electric Kettle',
    unitPrice: 40.0,
    amount: 6,
    totalPrice: 240.0,
  },
  {
    id: 32,
    product: 'Coffee Maker',
    unitPrice: 100.0,
    amount: 2,
    totalPrice: 200.0,
  },
  {
    id: 33,
    product: 'Blender',
    unitPrice: 70.0,
    amount: 3,
    totalPrice: 210.0,
  },
  {
    id: 34,
    product: 'Air Fryer',
    unitPrice: 150.0,
    amount: 1,
    totalPrice: 150.0,
  },
  {
    id: 35,
    product: 'Microwave Oven',
    unitPrice: 200.0,
    amount: 1,
    totalPrice: 200.0,
  },
  {
    id: 36,
    product: 'Refrigerator',
    unitPrice: 800.0,
    amount: 1,
    totalPrice: 800.0,
  },
  {
    id: 37,
    product: 'Washing Machine',
    unitPrice: 600.0,
    amount: 1,
    totalPrice: 600.0,
  },
  {
    id: 38,
    product: 'Dishwasher',
    unitPrice: 700.0,
    amount: 1,
    totalPrice: 700.0,
  },
  {
    id: 39,
    product: 'Vacuum Cleaner',
    unitPrice: 300.0,
    amount: 2,
    totalPrice: 600.0,
  },
  {
    id: 40,
    product: 'Hair Dryer',
    unitPrice: 50.0,
    amount: 4,
    totalPrice: 200.0,
  },
  {
    id: 41,
    product: 'Electric Toothbrush',
    unitPrice: 40.0,
    amount: 5,
    totalPrice: 200.0,
  },
  {
    id: 42,
    product: 'Shaver',
    unitPrice: 60.0,
    amount: 3,
    totalPrice: 180.0,
  },
  {
    id: 43,
    product: 'Air Conditioner',
    unitPrice: 1000.0,
    amount: 1,
    totalPrice: 1000.0,
  },
  {
    id: 44,
    product: 'Heater',
    unitPrice: 200.0,
    amount: 1,
    totalPrice: 1000.0,
  },
];
